trigger:
  none

variables:
# Docker Registry
  dockerRegistry: 'ashudevops'
  imageTag: '$(Build.BuildId)'
  imageNAme1: 'ashu290996/Chabot-ui'
  #mavenCacheFolder: $(Pipeline.Workspace)/.m2/repository
  # SonarQube
  sonarQubeServiceConnection: 'sonarQube'
  sonarProjectKey: 'Chabot-ui'
  
  # Kubernetes
  kubernetesServiceConnection: 'k8s-prod-connection'
  stagingNamespace: 'staging'
  productionNamespace: 'production'
  
  # Build
  #vmImageName: 'ubuntu-latest'
  
  # Security Thresholds
  trivySeverity: 'HIGH,CRITICAL'
  owaspFailOnCVSS: 7

pool:
 name: default


stages:
    - stage: 
      displayName: 'Installing dependencis'
      jobs:
          - job: 
            displayName: 'Installing Nodejs'
            steps:
            
            - task: NodeTool@0
              inputs:
                versionSource: 'spec'
                versionSpec: '18.x'
            - task: CmdLine@2
              displayName: 'Installing dependencies'
              inputs:
                  script: |
                    npm install
                    npm run build --if-present
                    npm run test --if-present

    - stage: SonarQube
      displayName: 'SonarQube Analysis'
      jobs:
          - job: SonarQubeAnalysis
            steps: 

            - task: SonarQubePrepare@8
              displayName: 'Prepare SonarQube Analysis'
              inputs:
                SonarQube: '$(sonarQubeServiceConnection)'
                scannerMode: 'CLI'
                configMode: 'manual'
                cliProjectKey: 'Chatbot-UI'
                cliProjectName: 'Chatbot-UI'
                cliSources: '$(System.DefaultWorkingDirectory)'
                  
            - task: SonarQubeAnalyze@8
              displayName: 'SonarQubeAnalyze'
              inputs:
                jdkversion: 'JAVA_HOME_21_X64'

            - task: SonarQubePublish@8
              displayName: 'SonarQubePublish'
              continueOnError: false
              inputs:
                pollingTimeoutSec: '300'

    - stage:
      displayName: 'OWASP'
      jobs:
        - job: 
          displayName: 'OWASP scanner'
          steps:
            - task: dependency-check-build-task@6
              continueOnError: true
              inputs:
                projectName: 'Chatbot-UI'
                scanPath: '$(System.DefaultWorkingDirectory)'
                format: 'HTML'
                uploadReports: true
    

    - stage: Trivyscan
      jobs:
        - job: Trivyfilescan
          displayName: 'Trivyfilescan'
          steps:
            - script: trivy fs . --severity $(trivySeverity) --format table --output $(Build.ArtifactStagingDirectory)/trivy-fs-backend-report.txt
              workingDirectory: Chatbot-UI/components

            - script:  cat $(Build.ArtifactStagingDirectory)/trivy-fs-backend-report.txt
              workingDirectory: Chatbot-UI/components

            # - script: trivy fs . --severity $(trivySeverity) --format table --output $(Build.ArtifactStagingDirectory)/trivy-fs-frontend-report.txt
            #   workingDirectory: wanderlust-3tier-project/frontend

            # - script:  cat $(Build.ArtifactStagingDirectory)/trivy-fs-frontend-report.txt
            #   workingDirectory: wanderlust-3tier-project/frontend  


    - stage: DockerImage
      jobs:
        - job: DockerbuildfrontImage
          displayName: 'DockerbuildfrontImage'
          steps:

          - task: Docker@2
            inputs:
              containerRegistry: '$(dockerRegistry)'
              repository: '$(imageName1)'
              command: 'buildAndPush'
              Dockerfile: '**Dockerfile'
              tags: |
                $(imageTag)
                latest

        - job: DockerbuildbackenedImage
          displayName: 'DockerbuildbackenedImage'
          steps:
            - task: Docker@2
              inputs:
                containerRegistry: '$(dockerRegistry)'
                repository: '$(imageName2)'
                command: 'buildAndPush'
                Dockerfile: '**Dockerfile'
                tags: |
                  $(imageTag)
                  latest

 # =====================================================
 # STAGE 7: TRIVY SCAN - DOCKER IMAGE
 # =====================================================
    - stage: Trivy_ImageScan
      displayName: 'Trivy Image Scan'
      #dependsOn: DockerBuild
      jobs:
        - job: TrivyImageScan
          displayName: 'Scan Docker frontend Image'
          steps:
          # - script: |
          #     # Install Trivy
          #     curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.48.0
          #   displayName: 'Install Trivy'

          - task: Docker@2
            displayName: 'Docker Login'
            inputs:
              containerRegistry: '$(dockerRegistry)'
              command: 'login'

          - script: |
              echo "=== Scanning Docker image for vulnerabilities ==="
              
              # Pull the image
              docker pull $(dockerRegistry)/$(imageName1):$(imageTag) || true
              
              # Table format for console
              trivy image $(dockerRegistry)/$(imageName1):$(imageTag) \
                --severity $(trivySeverity) \
                --format table \
                --output $(Build.ArtifactStagingDirectory)/trivy-image-report.txt
              
              # JSON format for parsing
              trivy image $(dockerRegistry)/$(imageName1):$(imageTag) \
                --severity $(trivySeverity) \
                --format json \
                --output $(Build.ArtifactStagingDirectory)/trivy-image-report.json
              
              # SARIF format for Azure DevOps Security tab
              trivy image $(dockerRegistry)/$(imageName1):$(imageTag) \
                --severity $(trivySeverity) \
                --format sarif \
                --output $(Build.ArtifactStagingDirectory)/trivy-image-report.sarif
              
              # HTML report
              trivy image $(dockerRegistry)/$(imageName1):$(imageTag) \
                --severity $(trivySeverity) \
                --format template \
                --template "@contrib/html.tpl" \
                --output $(Build.ArtifactStagingDirectory)/trivy-image-report.html || true
              
              # Display results
              cat $(Build.ArtifactStagingDirectory)/trivy-image-report.txt
              
              # Fail on critical vulnerabilities
              trivy image $(dockerRegistry)/$(imageName1):$(imageTag) \
                --severity CRITICAL \
                --exit-code 1 \
                --ignore-unfixed || {
                  echo "##vso[task.logissue type=error]CRITICAL vulnerabilities found in Docker image!"
                  exit 1
                }
            displayName: 'Trivy Image Scan'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Trivy Image Report'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'trivy-image-report'
            condition: always()

        - job: TrivyImageScan2
          displayName: 'Scan Docker backened Image'
          steps:
              # - script: |
              #     # Install Trivy
              #     curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.48.0
              #   displayName: 'Install Trivy'

          - task: Docker@2
            displayName: 'Docker Login'
            inputs:
              containerRegistry: '$(dockerRegistry)'
              command: 'login'

          - script: |
                echo "=== Scanning Docker image for vulnerabilities ==="
                
                # Pull the image
                docker pull $(dockerRegistry)/$(imageName2):$(imageTag) || true

                trivy image $(dockerRegistry)/$(imageName2):$(imageTag) \
                  --severity $(trivySeverity) \
                  --format table \
                  --output $(Build.ArtifactStagingDirectory)/trivy-image-report.txt

                # JSON format for parsing
                trivy image $(dockerRegistry)/$(imageName2):$(imageTag) \
                  --severity $(trivySeverity) \
                  --format json \
                  --output $(Build.ArtifactStagingDirectory)/trivy-image-report.json
              
                # SARIF format for Azure DevOps Security tab
                trivy image $(dockerRegistry)/$(imageName2):$(imageTag) \
                  --severity $(trivySeverity) \
                  --format sarif \
                  --output $(Build.ArtifactStagingDirectory)/trivy-image-report.sarif
                
                # HTML report
                trivy image $(dockerRegistry)/$(imageName2):$(imageTag) \
                  --severity $(trivySeverity) \
                  --format template \
                  --template "@contrib/html.tpl" \
                  --output $(Build.ArtifactStagingDirectory)/trivy-image-report.html || true
                
                # Display results
                cat $(Build.ArtifactStagingDirectory)/trivy-image-report.txt
                
                # Fail on critical vulnerabilities
                trivy image $(dockerRegistry)/$(imageName2):$(imageTag) \
                  --severity CRITICAL \
                  --exit-code 1 \
                  --ignore-unfixed || {
                    echo "##vso[task.logissue type=error]CRITICAL vulnerabilities found in Docker image!"
                    exit 1
                  }
                displayName: 'Trivy Image Scan2'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Trivy Image Report2'
            inputs:
                pathToPublish: '$(Build.ArtifactStagingDirectory)'
                artifactName: 'trivy-image-report2'
            condition: always()

                


            
            
